In [1]:
corpus = [
    "sunday is my favoute sunday",
    "I hate mondays after sunday",
    "Tuesday is good day as its my birthday but sunday",
    "wednesday is a holiday for festival",
    "I dont like to come on thrusday",
    "friday i have to come early",
    "saturday i passion to work more"
]

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer, TfidfTransformer
vectorizer = TfidfVectorizer()
vectorizer.fit_transform(corpus)

<7x31 sparse matrix of type '<class 'numpy.float64'>'
	with 39 stored elements in Compressed Sparse Row format>

In [8]:
vectorizer.fit_transform(corpus).toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.48758994, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.34595964, 0.        , 0.        , 0.        ,
        0.        , 0.40474152, 0.        , 0.        , 0.        ,
        0.69191927, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.53426056, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.53426056, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.53426056,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37907384, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.33911151, 0.33911151, 0.33911151, 0.        ,
        0.33911151, 0.        , 0.        , 0.        , 0.        ,
      

In [4]:
cv1 = CountVectorizer()
datatrain = cv1.fit_transform(corpus)
word2tfidft = dict(zip(cv1.get_feature_names(), vectorizer.idf_))
word2tfidft

{'after': 2.386294361119891,
 'as': 2.386294361119891,
 'birthday': 2.386294361119891,
 'but': 2.386294361119891,
 'come': 1.9808292530117262,
 'day': 2.386294361119891,
 'dont': 2.386294361119891,
 'early': 2.386294361119891,
 'favoute': 2.386294361119891,
 'festival': 2.386294361119891,
 'for': 2.386294361119891,
 'friday': 2.386294361119891,
 'good': 2.386294361119891,
 'hate': 2.386294361119891,
 'have': 2.386294361119891,
 'holiday': 2.386294361119891,
 'is': 1.6931471805599454,
 'its': 2.386294361119891,
 'like': 2.386294361119891,
 'mondays': 2.386294361119891,
 'more': 2.386294361119891,
 'my': 1.9808292530117262,
 'on': 2.386294361119891,
 'passion': 2.386294361119891,
 'saturday': 2.386294361119891,
 'sunday': 1.6931471805599454,
 'thrusday': 2.386294361119891,
 'to': 1.6931471805599454,
 'tuesday': 2.386294361119891,
 'wednesday': 2.386294361119891,
 'work': 2.386294361119891}

In [5]:
testdata = ['i like festival', 'i love vacation in festival', 'i interested in work in festival']

In [9]:
cv11 = CountVectorizer()
test_text = cv11.fit_transform(testdata)
vectorizer1 = TfidfVectorizer()
vectorizer1.fit_transform(testdata)
word2tfidftt = dict(zip(cv11.get_feature_names(), vectorizer1.idf_))
word2tfidftt

{'festival': 1.0,
 'in': 1.2876820724517808,
 'interested': 1.6931471805599454,
 'like': 1.6931471805599454,
 'love': 1.6931471805599454,
 'vacation': 1.6931471805599454,
 'work': 1.6931471805599454}

In [10]:
vectorizer1.idf_

array([1.        , 1.28768207, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718])

In [11]:
vectorizer.idf_

array([2.38629436, 2.38629436, 2.38629436, 2.38629436, 1.98082925,
       2.38629436, 2.38629436, 2.38629436, 2.38629436, 2.38629436,
       2.38629436, 2.38629436, 2.38629436, 2.38629436, 2.38629436,
       2.38629436, 1.69314718, 2.38629436, 2.38629436, 2.38629436,
       2.38629436, 1.98082925, 2.38629436, 2.38629436, 2.38629436,
       1.69314718, 2.38629436, 1.69314718, 2.38629436, 2.38629436,
       2.38629436])

In [ ]:
'festival': 2.386294361119891,  'festival': 1.0,